# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/clean'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'

# bind to our development version of the locale_selector
$:.unshift File.join(File.dirname(__FILE__), '..', '..', 'lib')
require 'locale_selector/gettext_tasks'

 CLOBBER.include('po/default.pot')

namespace :test do
  desc 'Regenerate po files'
  task 'regenerate_po' do
    sh 'rake gettext:updatepo lang=de'
  end

  task :integration => ['clobber', 'environment', 'db:schema:load', 'db:test:prepare', 'test:regenerate_po']
end

